### ISSUE TITLE
make_geocube function kills kernel

### ISSUE THREAD

**Issue by WHBSpeiser** [corteva/geocube#123]
Hello! Ever since the new update whenever I use the make_geocube function my kernel dies. I tried using code and data that I have successfully ran in the pass and still have yielded the same result... Thank you so much for these tools they are invaluable!

**Comment by WHBSpeiser** [comment]
geocube v0.3.2

GDAL deps:
         fiona: 1.8.21
   GDAL[fiona]: 3.4.1
      rasterio: 1.3.0
GDAL[rasterio]: 3.5.1

Python deps:
       appdirs: 1.4.4
         click: 8.0.4
     geopandas: 0.11.0
       odc_geo: None
     rioxarray: 0.11.1
        pyproj: 3.3.1
        xarray: 2022.3.0

System:
        python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
    executable: /home/williamcoast/anaconda3/envs/coast_corr/bin/python
       machine: Linux-5.19.0-76051900-generic-x86_64-with-glibc2.35

**Comment by snowman2** [comment]
Your GDAL versions for rasterio and Fiona differ. That makes me believe that you didn't use conda to install them. Since you are using conda, I highly recommend installing rasterio and Fiona using conda. Please try again after re-creating a new environment following the instructions here: https://corteva.github.io/geocube/stable/installation.html

**Comment by WHBSpeiser** [comment]
Seems to have done the trick! Thanks for the help.
