### ISSUE TITLE
Error when importing make_geocube

### ISSUE THREAD

**Issue by kross0926** [corteva/geocube#20]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your code here
from geocube.api.core import make_geocube
```
#### Problem description
It appears to be an issue in spyder, since the command and package works when running it in a cmd prompt python console.

It looks like something to do with the rasterio dependency but when I import rasterio on its own it imports fine.
Any suggestions on how to fix spyder?

#### Expected Output
none
#### Output of ``geocube --version 0.0.11``

<details>

Traceback (most recent call last):

  File "rasterio\_crs.pyx", line 215, in rasterio._crs._CRS.from_epsg

  File "rasterio\_err.pyx", line 182, in rasterio._err.exc_wrap_int

CPLE_AppDefinedError: PROJ: proj_create_from_database: Cannot find proj.db

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-24-613d73fbe2cc>", line 1, in <module>
    from geocube.api.core import make_geocube

  File "C:\Anaconda3\lib\site-packages\geocube\api\core.py", line 7, in <module>
    from geocube.geo_utils.geobox import GeoBoxMaker

  File "C:\Anaconda3\lib\site-packages\geocube\geo_utils\geobox.py", line 9, in <module>
    from datacube.utils import geometry

  File "C:\Anaconda3\lib\site-packages\datacube\utils\geometry\__init__.py", line 52, in <module>
    from ._warp import (

  File "C:\Anaconda3\lib\site-packages\datacube\utils\geometry\_warp.py", line 10, in <module>
    _WRP_CRS = rasterio.crs.CRS.from_epsg(3857)

  File "C:\Anaconda3\lib\site-packages\rasterio\crs.py", line 321, in from_epsg
    obj._crs = _CRS.from_epsg(code)

  File "rasterio\_crs.pyx", line 217, in rasterio._crs._CRS.from_epsg

CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: Cannot find proj.db
</details>

**Comment by kross0926** [comment]
I have figured out how to fix this issue.

I had to activate the environment from the command line then open spyder from there
it appears to have somthing to do with the rasterio and proj dependencies
https://github.com/mapbox/rasterio/issues/1850
```
conda activate myenv
spyder
```

**Comment by openSourcerer9000** [comment]
The above did not work for me, see below:

I'm seeing this same issue across the GIS py universe. After banging my head against the wall the entire day on it, this is what worked for me:

The issue first popped up after installing PostGIS. A second PROJ version is what's screwing things up. I am on Windows with a conda env. The issue only happened in a jupyter kernel for some reason, and it ran all the way up the stack: pyproj, rasterio, rioxarray, geocube.

This temporary fix works for pyproj only. Not for anything higher level:
https://pyproj4.github.io/pyproj/stable/gotchas.html#internal-proj-error-sqlite-error-on-select

**The temporary solution:**
This finally worked for me. Run the PostGIS uninstaller, MANUALLY delete the PROJ_LIB system environment variable. Close jupyter lab and associated server, $ conda deactivate myEnv. Reactivate and reopen jupyter (or whatever app was giving you problems.) 

The problem here is... I just installed PostGIS. As I will need to maintain both installs of PROJ, this remains an outstanding issue. Unfortunately, the issue is so large it gets replicated across the GIS stack, so any issue that pops up is immediately closed with a finger pointed at some other lib involved.
